### ISSUE TITLE
Shader fails to compile on current radeon/mesa git

### ISSUE THREAD

**Issue by EoD** [turol/smaaDemo#2]
When I try to execute the program (after removing the icf from LDFLAGS), the program crashes:
```
$ ./binaries/smaaDemo-bin
Number of displays detected: 1
Number of display modes for display 0 : 22
Display mode 0 : width 1920, height 1080, BPP 24
Display mode 1 : width 1680, height 1050, BPP 24
Display mode 2 : width 1600, height 1200, BPP 24
Display mode 3 : width 1440, height 900, BPP 24
Display mode 4 : width 1400, height 1050, BPP 24
Display mode 5 : width 1280, height 1024, BPP 24
Display mode 6 : width 1280, height 1024, BPP 24
Display mode 7 : width 1280, height 960, BPP 24
Display mode 8 : width 1152, height 864, BPP 24
Display mode 9 : width 1024, height 768, BPP 24
Display mode 10 : width 1024, height 768, BPP 24
Display mode 11 : width 1024, height 768, BPP 24
Display mode 12 : width 832, height 624, BPP 24
Display mode 13 : width 800, height 600, BPP 24
Display mode 14 : width 800, height 600, BPP 24
Display mode 15 : width 800, height 600, BPP 24
Display mode 16 : width 800, height 600, BPP 24
Display mode 17 : width 720, height 400, BPP 24
Display mode 18 : width 640, height 480, BPP 24
Display mode 19 : width 640, height 480, BPP 24
Display mode 20 : width 640, height 480, BPP 24
Display mode 21 : width 640, height 480, BPP 24
VSync is on
ARB_direct_state_access found
Vertex array objects enabled
Sampler objects enabled
GL vendor: "X.Org"
GL renderer: "Gallium 0.4 on AMD BARTS (DRM 2.43.0, LLVM 3.7.0)"
GL version: "3.3 (Core Profile) Mesa 11.2.0-devel (git-57fc0dd)"
GLSL version: "3.30"
shader "fxaa.frag" info log:
0:897(16): error: no matching function for call to `textureGather(sampler2D, vec2, int)'; candidates are:
0:898(16): error: no matching function for call to `textureGatherOffset(sampler2D, vec2, ivec2, int)'; candidates are:

info log end
caught std::exception "shader compile failed"
terminate called after throwing an instance of 'std::runtime_error'
  what():  shader compile failed
Aborted
```

According to https://www.opengl.org/sdk/docs/man/html/textureGatherOffset.xhtml the function is only available on GLSL 4 and above.

According to http://mesamatrix.net/, my card (using r600) should support GL_ARB_texture_gather. Why doesn't it compile?
I assume there is a missing ``pushLine("#extension GL_ARB_texture_gather : enable");`` somewhere.

As a fallback, could you disable FXAA on GLSL version < 4? The SMAA demo should run nevertheless.

**Comment by EoD** [comment]
Actually, you need both. I added them on line [smaaDemo.cpp:704](https://github.com/turol/smaaDemo/blob/master/demo/smaaDemo.cpp#L704), after the if bracket and the shader compiled.

```
           pushLine("#extension GL_ARB_texture_gather : enable");
           pushLine("#extension GL_ARB_gpu_shader5 : enable");
```

**Comment by turol** [comment]
These should be enabled already, but only if they're supported. Enabling them if they're not supported causes warnings from shader compiler. I think the error happens because the bundled version of GLEW doesn't properly handle core contexts. I'll update it.

**Comment by turol** [comment]
@EoD Try it now.

**Comment by EoD** [comment]
Thanks, that fixed it!

**Comment by turol** [comment]
While you're at it you might want to kick @nigels-com to finish the official core version of GLEW.

**Comment by EoD** [comment]
It seems like he already got a v5 of the core-support branch https://github.com/nigels-com/glew/tree/core-context5 . How would you suggest to give @nigels-com a push?

**Comment by turol** [comment]
There's a branch but no official release yet. And I think us mentioning him should be enough :)

**Comment by nigels-com** [comment]
Yeah, the core-context5 branch is likely to get merged to master and released, probably around Christmas time.  The more testing, the better!
