### ISSUE TITLE
Boost Version

### ISSUE THREAD

**Issue by tn12787** [turol/smaaDemo#3]
Using boost on Ubuntu 16.04 I can't build this package. Compilation errors are coming from boost, and I'm certain there's a version mismatch.

Which version of boost should this project be built against?

Thanks!

**Comment by turol** [comment]
I'm using Debian stable and testing, with boost versions 1.55, 1.62 and 1.63 on various computers. Those should work.

What error message are you getting? What compiler version are you using?
