### ISSUE TITLE
Window start up like one second and shut down immediately

### ISSUE THREAD

**Issue by OkazakiNaoki** [turol/smaaDemo#4]
I use VS2017 community 64bits to compile the Debug version OpenGL and Vulkan.
Both start then shut down immediately, and I don't know why since it already show no more error.
Have you encounter this before? What did I do wrong.

Boost downloaded and built it as 64 bits. Include and library.
Vulkan SDK installed. Include and library.
SDL2 dev kit downloaded. Include and library.
SPIRV-Cross and SPIRV-Tools both cmake 64 bits and built successfully.

**Comment by turol** [comment]
Program must be started with the top-level directory as the current directory. VS defaults instead to the `windows` directory and it's part of the user configuration, not the project itself. Go to debug settings and change it.
