### ISSUE TITLE
IMGUI and background issue

### ISSUE THREAD

**Issue by OkazakiNaoki** [turol/smaaDemo#5]
I am sorry, I have two question left.
(1).
I did successfully run your program.
But once I click the TAA enable button it would cause exception. (with SMAA)
It point to /renderer/redererinternal.h line 81 : handle.handle != 0
However, I press 'T' button instead, it would be fine and work.
Is IMGUI bugged? or I did something wrong again :P

(2).
If I background the window, it call abort() and the program shut down.
I saw it abort() is define as UNREACHABLE()
So this is intend to doing so?

Thank you for answered me yesterday.
Once all the execute issue is cleared, I will look into your code.
Your code is clean and a good learning source, thank you again!

**Comment by turol** [comment]
(1) is probably my bug. I'm currently doing some major refactoring and TAA is broken in my latest code but I'll try to test before pushing the new version.

(2) Which UNREACHABLE was that? It should never happen. Putting the program into background works on Linux, can't test Windows just now.

**Comment by OkazakiNaoki** [comment]
About (2), it just tell me it called abort(). Since it's not execute in VS environment, it didn't tell me which line this time.
