### ISSUE TITLE
throwing an instance of 'vk::LayerNotPresentError'

### ISSUE THREAD

**Issue by MrSDZhou** [turol/smaaDemo#6]
Hi, when I run the command "./smaaDemo-bin --debug -f --width 500 --height 500 patch_15104.png", I got the following issues:
"terminate called after throwing an instance of 'vk::LayerNotPresentError'
  what():  vk::createInstance: ErrorLayerNotPresent
Aborted (core dumped)
"
I have successfully make the program, So, can anybody tell me what's wrong with this, and how to resolve it.

**Comment by turol** [comment]
Do you have the debug layers installed? Did you install Vulkan SDK from LunarG or your distro packages?

**Comment by MrSDZhou** [comment]
ok, thanks. I have run it successfully, just because I can't debug it. But I came across another  problem, that is when I run it for a while, it is shut down suddenly, and the error log is "smaaDemo-bin: ../renderer/VulkanRenderer.cpp:734: renderer::RendererImpl::~RendererImpl(): Assertion `persistentMapping' failed.
Aborted (core dumped)"
I was wondering the reasons for this issue.

**Comment by turol** [comment]
That's not the real issue, that's just an assertion failing on unclean shutdown. The real issue was something else, probably an exception. Pastebin full output and log if you want more help.
