### ISSUE TITLE
16RGBA format

### ISSUE THREAD

**Issue by jbghzawsze** [turol/smaaDemo#8]
How would one go about extending the format to RGBA16? Are there any problems other than add Format enums?

**Comment by turol** [comment]
There is already `RGBA16Float` format
https://github.com/turol/smaaDemo/blob/08e1387832abce6e2949d949aeb43abb566ffad9/renderer/Renderer.h#L397

To add new formats just add it to the enum and fix all warnings/errors that result. Mostly adding it to switches which convert to native format enums.

**Comment by turol** [comment]
I think that's it but just try it and find out.
